### ISSUE TITLE
Usage without Transformation

### ISSUE THREAD

**Issue by jahirfiquitiva** [zjupure/GlideWebpDecoder#31]
Hi ... I would like to know how I can use this decoder when I don't want to apply any kind of transformation (or use the default one).

Thanks in advance

**Comment by zjupure** [comment]
You should read glide docs first, If you do not want to apply transformation, you just do not call `transform()` or `optionalTransfrom()` method with Glide load.

```
GlideApp.with(mContext)
        .load(url)
        //.optionalTransform(circleCrop)
       // .optionalTransform(WebpDrawable.class, new WebpDrawableTransformation(circleCrop))
        .into(imageView);
```

**Comment by zjupure** [comment]
You just need to add this library dependency in your `build.gradle` , and the webp decoder will be auto registered into glide decoder pipelines. You can see sample project for basic usage.

**Comment by YouheiLee** [comment]
but if you do not have a transformation, you will not be able to load webp. when you load webp without transformation, you will got a exception:
java.lang.IllegalArgumentException: Unable to convert com.bumptech.glide.integration.webp.decoder.WebpDrawable@19c496f to a Bitmap

cause if you don't specific a transformation, then Glide will use DrawableTransformation, and DrawableTransformation will throw this exception since Resource<Bitmap> is null;

![image](https://user-images.githubusercontent.com/8281520/71148846-c3ca1c80-2267-11ea-8378-3fe8eae08b3d.png)
